name: Spond log archiver

on:
  workflow_dispatch:

jobs:
  get_log:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: log

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        cache: 'pip'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Get log
      run: python spond_log.py "${{ secrets.SPOND_USERNAME }}" "${{ secrets.SPOND_PASSWORD }}"

    - name: Git config
      run: |
        git config --global user.email "<>"
        git config --global user.name "GitHut Actions Bot"

    - name: Commit
      run: |
        git add lockerley*
        git commit -m "New log"
        git push origin master
